# Use Nginx for serving static files
FROM nginx:alpine

# Copy the built React app into the Nginx container
COPY build/ /usr/share/nginx/html

# Expose the port
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
