words = {
    'en': {
        'logo': 'Factee',
        'welcome': 'Welcome to the Factee',
        'thesis': 'Reference someone. Prove your words. Mediate between source and fact',
        'fact': 'fact',
        'facts': 'Facts',
        'create_fact': 'Create fact',
        'source': 'source',
        'sources': 'Sources',
        'create_source': 'Create source',
        'add_source': 'Add source',
        'login': 'Login',
        'logout': 'Logout',
        'user_info': 'User info',
        'name': 'Name',
        'username': 'Username',
        'email': 'Email',
        'roles': 'Roles',
        'permissions': 'Permissions',
        'token_type': 'Token type',
        'created_at': 'Created at',
        'create': 'Create *',
        'create_a_new': 'Create a new *',
        'status': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'total_labels_on_facts': 'Total labels on facts',
        'you_are_not_authenticated': 'You are not authenticated',
        'developer_info': 'Developer info',
        'title': 'Title',
        'context': 'Context',
        'year': 'Year',
        'quote': 'Quote',
        'search_source': 'Search source',
        'select_source': 'Select a source',
        'select_a_knowledge_type': 'Select a knowledge type',
        'source_link': 'Source link',
        'author': 'Author',
        'type': 'Type',
        'mediator': 'Mediator',
        'account_console': 'Account console',
        'how_to_create': 'How to create * ?',
        'how_to': 'How to',
        'warning': 'Warning!',
        'redirect_warning': 'You want to go to another site that may contain malicious. This site is not responsible for the content of links. It is recommended to search for sources with the names of the authors, year and title.',

        'page': 'Page',
        'p': 'p',
        'sort_by': 'Sort by',
        'first': 'First',
        'last': 'Last',
        'next': 'Next',
        'previous': 'Previous',
        'of': 'of',
        'no_results': 'No results',
        'copied': 'Copied!',
        'deleted_text': 'This * was deleted. Current * could have been changed by anyone by link!',
        'baked': 'baked',
        'user_avatar': 'User avatar',
        'verified': 'Verified',
        'not_verified': 'Not Verified',
        
        'default': 'Default',
        'profile': 'Profile',
        'fact_list': 'Fact list',
        'source_list': 'Source list',

        # Types
        'Science': 'Science',
        'Mystic': 'Mystic',
        'Religion': 'Religion',
        'Domestic': 'Domestic',

        # Labels
        'upvote': 'Upvote',
        'downvote': 'Downvote',
        'true': 'True',
        'fake': 'Fake',
        'free': 'Free',
        'paid': 'Paid',

        'not_subscriber': 'Free profile support only * facts. You can login into patreon in your profile.',
        'max_subscriber': 'Paid profile only allows * facts.',
    },
    'ru': {
        'logo': 'Factee',
        'welcome': 'Добро пожаловать в Factee',
        'thesis': 'Сошлитесь на кого-то. Докажите свои слова. Медиируйте между источником и фактом',
        'fact': 'факт',
        'facts': 'Факты',
        'create_fact': 'Создать факт',
        'source': 'источник',
        'sources': 'Источники',
        'create_source': 'Создать источник',
        'add_source': 'Добавить источник',
        'login': 'Войти',
        'logout': 'Выйти',
        'user_info': 'Информация о пользователе',
        'name': 'Имя',
        'username': 'Имя пользователя',
        'email': 'Электронная почта',
        'roles': 'Роли',
        'permissions': 'Разрешения',
        'token_type': 'Тип токена',
        'created_at': 'Создано',
        'create': 'Создать *',
        'create_a_new': 'Создать новый *',
        'status': 'Статус',
        'active': 'Активный',
        'inactive': 'Неактивный',
        'total_labels_on_facts': 'Всего меток на фактах',
        'you_are_not_authenticated': 'Вы не авторизованы',
        'developer_info': 'Информация о разработчике',
        'title': 'Название',
        'context': 'Контекст',
        'year': 'Год',
        'quote': 'Цитата',
        'search_source': 'Поиск источника',
        'select_source': 'Выберите источник',
        'select_a_knowledge_type': 'Выберите тип знаний',
        'source_link': 'Ссылка на источник',
        'author': 'Автор',
        'type': 'Тип',
        'mediator': 'Посредник',
        'account_console': 'Консоль аккаунта',
        'how_to_create': 'Как создать *?',
        'how_to': 'Как',
        'warning': 'Предупреждение!',
        'redirect_warning': 'Вы хотите перейти на другой сайт, который может содержать вредоносные материалы. Этот сайт не несет ответственности за содержимое ссылок. Рекомендуется искать источники по имени автора, году и названию.',

        'page': 'Страница',
        'p': 'с.',
        'sort_by': 'Сортировать по',
        'first': 'Первый',
        'last': 'Последний',
        'next': 'Следующий',
        'previous': 'Предыдущий',
        'of': 'из',
        'no_results': 'Нет результатов',
        'copied': 'Скопировано!',
        'deleted_text': 'Этот * был удален. Текущий * мог быть изменен кем угодно по ссылке!',
        'baked': 'запечено',
        'user_avatar': 'Аватар пользователя',
        'verified': 'Подтвержден',
        'not_verified': 'Не подтвержден',

        'default': 'По умолчанию',
        'profile': 'Профиль',
        'fact_list': 'Список фактов',
        'source_list': 'Список источников',

        # Типы
        'Science': 'Наука',
        'Mystic': 'Мистика',
        'Religion': 'Религия',
        'Domestic': 'Быт',

        # Метки
        'upvote': 'Лайк',
        'downvote': 'Дизлайк',
        'true': 'Правда',
        'fake': 'Фейк',
        'free': 'Бесплатно',
        'paid': 'Платно',

        'not_subscriber': 'Бесплатная поддержка профиля только для * фактов. Вы можете войти в patreon в своем профиле.',
        'max_subscriber': 'Платный профиль допускает только * фактов.',
    },
    'kz': {
        'logo': 'Factee',
        'welcome': 'Factee-ге қош келдіңіз',
        'thesis': 'Біреуге сілтеме жасаңыз. Сөздеріңізді дәлелдеңіз. Дереккөз бен фактінің арасында дәнекер болыңыз',
        'fact': 'факт',
        'facts': 'Фактлер',
        'create_fact': 'Факт жасау',
        'source': 'дереккөз',
        'sources': 'Дереккөздер',
        'create_source': 'Дереккөз жасау',
        'add_source': 'Дереккөз қосу',
        'login': 'Кіру',
        'logout': 'Шығу',
        'user_info': 'Пайдаланушы ақпараты',
        'name': 'Аты',
        'username': 'Пайдаланушы аты',
        'email': 'Электрондық пошта',
        'roles': 'Рөлдер',
        'permissions': 'Рұқсаттар',
        'token_type': 'Токен түрі',
        'created_at': 'Жасалған уақыты',
        'create': '* жасау',
        'create_a_new': 'Жаңа * жасау',
        'status': 'Күйі',
        'active': 'Белсенді',
        'inactive': 'Белсенді емес',
        'total_labels_on_facts': 'Фактлердегі жалпы белгілер',
        'you_are_not_authenticated': 'Сіз аутентификацияланбағансыз',
        'developer_info': 'Әзірлеуші туралы ақпарат',
        'title': 'Тақырып',
        'context': 'Контекст',
        'year': 'Жыл',
        'quote': 'Дәйексөз',
        'search_source': 'Дереккөз іздеу',
        'select_source': 'Дереккөзді таңдау',
        'select_a_knowledge_type': 'Білім түрін таңдау',
        'source_link': 'Дереккөз сілтемесі',
        'author': 'Автор',
        'type': 'Түрі',
        'mediator': 'Дәнекер',
        'account_console': 'Тіркелгі консолі',
        'how_to_create': '* қалай жасауға болады?',
        'how_to': 'Қалай',
        'warning': 'Ескерту!',
        'redirect_warning': 'Сіз зиянды болуы мүмкін басқа сайтқа өтпекшісіз. Бұл сайт сілтемелердің мазмұнына жауапты емес. Дереккөздерді автордың аты-жөні, жылы және тақырыбы арқылы іздеуді ұсынамыз.',

        'page': 'Бет',
        'p': 'б',
        'sort_by': 'Сұрыптау',
        'first': 'Бірінші',
        'last': 'Соңғы',
        'next': 'Келесі',
        'previous': 'Алдыңғы',
        'of': '/',
        'no_results': 'Нәтиже жоқ',
        'copied': 'Көшірілді!',
        'deleted_text': 'Бұл * жойылды. Қазіргі * кез келген адам сілтеме арқылы өзгерте алатын болуы мүмкін!',
        'baked': 'дайындалған',
        'user_avatar': 'Пайдаланушы аватары',
        'verified': 'Расталған',
        'not_verified': 'Расталмаған',

        'default': 'Әдепкі',
        'profile': 'Профиль',
        'fact_list': 'Факттер тізімі',
        'source_list': 'Дереккөздер тізімі',

        # Түрлері
        'Science': 'Ғылым',
        'Mystic': 'Мистика',
        'Religion': 'Дін',
        'Domestic': 'Тұрмыстық',

        # Белгілер
        'upvote': 'Қолдау',
        'downvote': 'Қарсы',
        'true': 'Шын',
        'fake': 'Жалған',
        'free': 'Тегін',
        'paid': 'Ақылы',

        'not_subscriber': 'Тегін профильді қолдау тек * фактілер. Сіз өзіңіздің профиліңізде patreon жүйесіне кіре аласыз.',
        'max_subscriber': 'Ақылы профиль тек * фактілерге рұқсат береді.',
    },
}