name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    runs-on: [self-hosted, linux]
    needs: build
    steps:
      - name: Deploy to Docker Swarm
        env:
          SWARM_MANAGER_IP: ${{ secrets.SWARM_MANAGER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SWARM_MANAGER_IP << 'EOF'
            cd /path/to/your/project
            docker stack deploy -c docker-compose.yml my_stack
            docker service update --force my_stack_backend
            docker service update --force my_stack_frontend
          EOF
